
# Copyright 2021, Battelle Energy Alliance, LLC All Rights Reserved

def examples():
	print('')
	print('')
	print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
	print('Predefined reactors available include:')
	print(' - INL_reactor_1.obj ')
	print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
	print('')
	print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
	print('Predefined mechanisms available include:')
	print(' - irreversible_adsorption.obj')
	print(' - reversible_adsorption.obj')
	print(' - irreversible_dissociative_adsorption.obj')
	print(' - reversible_dissociative_adsorption.obj')
	print(' - series_1.obj')
	print(' - series_2.obj')
	print(' - series_3.obj')
	print(' - parallel_1.obj')
	print(' - parallel_2.obj')
	print(' - multi_site_1.obj')
	print(' - multi_site_2.obj')
	print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
	print('')
	print('')